version: '3'
services:
  validateservice:
    build: .
    container_name: validateservice
    ports:
        - "5040:80"
    restart: always
    environment: 
      - TIMEOUT=360
      - GRACEFUL_TIMEOUT=360
      - MODULE_NAME=call_api
    